# Generated by Django 4.2.7 on 2023-12-24 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('house_name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('status', models.CharField(default='alive', max_length=40)),
            ],
        ),
    ]
