# Generated by Django 4.2.7 on 2023-12-26 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('got_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['house_name', '-age'], 'verbose_name': 'Character'},
        ),
    ]
