# Generated by Django 4.2.7 on 2023-12-07 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mebel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(verbose_name='Link')),
                ('price', models.DecimalField(decimal_places=10, max_digits=10)),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
