# Generated by Django 4.2.7 on 2023-12-07 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp1', '0002_mebel_delete_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mebel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
